[package]
name = "nodeauth/nodeauth-worker"
version = "2.3.18"
description = "NodeAuth 2FA Server for Wasmer Edge"

[dependencies]
"wasmer/node" = "*"

[[command]]
name = "nodeauth-worker"
module = "wasmer/node:node"
runner = "wasi"

[command.annotations.wasi]
main-args = ["backend/dist/wasmer/wasmer.js"]

[fs]
"/backend" = "backend"
"/frontend" = "frontend"
"/scripts" = "scripts"
