name: Deploy to Wasmer Edge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  wasmer:
    runs-on: ubuntu-latest
    name: "Deploy to Wasmer Edge"
    permissions:
      contents: read
    defaults:
      run:
        working-directory: platforms/wasmer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 24

      - name: Check Required Secrets
        run: |
          REQUIRED=(WASMER_TOKEN WASMER_OWNER)
          for var in "${REQUIRED[@]}"; do
            if [ -z "${!var}" ]; then
              echo "❌ Error: $var is missing."
              exit 1
            fi
          done
        env:
          WASMER_TOKEN: ${{ secrets.WASMER_TOKEN }}
          WASMER_OWNER: ${{ secrets.WASMER_OWNER }}

      - name: Inject Commit Hash & Platform
        run: node scripts/inject_vars.js --platform=wasmer

      - name: Update Wasmer Configuration
        run: |
          node scripts/update_wasmer.js
        env:
          WASMER_APP_NAME: ${{ secrets.WASMER_APP_NAME }}
          WASMER_OWNER: ${{ secrets.WASMER_OWNER }}

      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@24b15c95293d23f89c68bd40dac76338f773e924 # v3.1

      - name: Deploy NodeAuth to Wasmer Edge
        run: wasmer deploy --non-interactive --bump --build-remote --owner=${{ secrets.WASMER_OWNER }} --token=${{ secrets.WASMER_TOKEN }}
        working-directory: platforms/wasmer
            
      - name: Success Notification
        run: echo "🚀 NodeAuth deployed successfully to Wasmer Edge in Single-App mode!"
